# makefile to build 01-toy-app sample

all: sample

sample:
	# making 01-toy-app
	gcc src/*.c -o 01-toy-app
	# 01-toy-app sample has been built
	# invoke ./01-toy-app to run sample

clean:
	# cleaning up ...
	rm 01-toy-app
