# makefile to build 01-interact sample

all: sample

sample:
	# making 01-interact
	gcc src/*.c -o 01-interact
	# 01-interact sample has been built
	# invoke ./01-interact to run sample

clean:
	# cleaning up ...
	rm 01-interact
