# makefile to build 04-toy-app sample

all: sample

sample:
	# making 04-toy-app
	gcc src/*.c -o 04-toy-app
	# 04-toy-app sample has been built
	# invoke ./04-toy-app to run sample

clean:
	# cleaning up ...
	rm 04-toy-app
