# makefile to build 02-interact sample

all: sample

sample:
	# making 02-interact
	gcc src/*.c -o 02-interact
	# 02-interact sample has been built
	# invoke ./02-interact to run sample

clean:
	# cleaning up ...
	rm 02-interact
