# makefile to build 03-interact sample

all: sample

sample:
	# making 03-interact
	gcc src/*.c -o 03-interact
	# 03-interact sample has been built
	# invoke ./03-interact to run sample

clean:
	# cleaning up ...
	rm 03-interact
